Krbprojects.WebUI/Areas/KrbAdmin/Controllers/HomePageCRUDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Krbprojects.WebUI.Areas.KrbAdmin.Models.ViewModels;
using Krbprojects.WebUI.Models.DbContexts;
using Krbprojects.WebUI.Modules.HomePageModul;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Krbprojects.WebUI.Areas.KrbAdmin.Controllers
{
    //esas sehifede olan karuselin sekillerine deyisiklik etmek ucun 
    [Area("KrbAdmin")]
    public class HomePageCRUDController : Controller
    {
        readonly KrbProjectsBaseDbContext db;
        readonly IMediator mediator;
        public HomePageCRUDController(KrbProjectsBaseDbContext db, IMediator mediator)
        {
            this.db = db;
            this.mediator = mediator;
        }
        [Authorize(Policy = "admin.HomePageCRUD.index")]

        public async Task<IActionResult> Index()
        {
            var home = await db.HomePages.ToListAsync();
            return View(home);
        }
        [HttpGet]
        [Authorize(Policy = "admin.HomePageCRUD.Delete")]
        public async Task<IActionResult> Delete(long id)
        {
            var home = await db.HomePages.FirstOrDefaultAsync(h=>h.Id==id);
            return View(home);
        }
        [HttpPost]
        [Authorize(Policy = "admin.HomePageCRUD.Delete")]
        public async Task<IActionResult> DeleteConfirm(long id)
        {
            var home = await db.HomePages.Include(h=>h.Images).FirstOrDefaultAsync(h => h.Id == id);
            db.Remove(home);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Policy = "admin.HomePageCRUD.Create")]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "admin.HomePageCRUD.Create")]
        public async Task<IActionResult> Create(HomePageCreateCommand command)
        {
            var response = await mediator.Send(command);


            if (response > 0)
                return RedirectToAction(nameof(Index));

            return RedirectToAction(nameof(Create));
        }
        [Authorize(Policy = "admin.HomePageCRUD.Edit")]
        public async Task<IActionResult> Edit(HomePageSingleQuery query)
        {
            var response = await mediator.Send(query);

            if (response == null)
            {
                return NotFound();
            }

            var vm = new HomePageViewModel();
            vm.Id = response.Id;
            vm.Name = response.Name;
            vm.Images = response.Images;
            vm.Files = response.Files;
            return View(vm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "admin.HomePageCRUD.Edit")]
        public async Task<IActionResult> Edit(HomePageUpdateCommand command)
        {
            var response = await mediator.Send(command);

            if (response > 0)
                return RedirectToAction(nameof(Index));

            return View(command);

        }

    }
}

Krbprojects.WebUI/Areas/KrbAdmin/Views/HomePageCRUD/Create.cshtml
@model HomePage


@{
    ViewData["Title"] = "Create";
}

<form asp-controller="HomePageCRUD" asp-action="Create" enctype="multipart/form-data" method="post">
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>



    <div style="width: 600px;" class="imager-container" id="viewer1" name="images">
    </div>


    <div class="form-group">
        <input type="submit" value="Bazada Saxla" class="btn btn-success" />
    </div>

</form>
<a asp-controller="HomePageCRUD" asp-action="index" class="btn btn-primary">
    <spam>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-short" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z" />
        </svg>
    </spam>Geriyə

</a>


@section addcss{
    <script src="https://kit.fontawesome.com/1154e1d6ee.js" crossorigin="anonymous"></script>
    <link href="~/libs/multiple-imager-js/css/imager.css" rel="stylesheet" />
}


@section addjs{
    <script src="~/libs/jquery/jquery.min.js"></script>

    <script src="~/libs/multiple-imager-js/js/imager.js"></script>

    <script>
        $('#viewer1').imgadd({
            tnWidth: '120px',
            tnHeight: '120px',
            fontSize: '55px',
            plusInnerHtml: '',
            plusBtnClass: undefined
        });
    </script>
}

Krbprojects.WebUI/Areas/KrbAdmin/Views/HomePageCRUD/Delete.cshtml
@model HomePage
<h1>Silmək istədiyinizdən əminsinizsə davam edin</h1>

<form asp-controller="HomePageCRUD" asp-action="Deleteconfirm" asp-route-id="@Model.Id">
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Davam et" class="btn btn-success" />
    </div>
</form>
<a asp-controller="HomePageCRUD" asp-action="index" class="btn btn-primary">
    <spam>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-short" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z" />
        </svg>
    </spam>Geriyə

</a>

Krbprojects.WebUI/Areas/KrbAdmin/Views/HomePageCRUD/Edit.cshtml
@model HomePageViewModel
<form asp-controller="HomePageCRUD" asp-action="edit" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="@Model.Name" class="control-label"></label>
        <input asp-for="@Model.Name" class="form-control" />
        <span asp-validation-for="@Model.Name" class="text-danger"></span>
    </div>

    <
    <div class="form-group">
        <div style="width: 600px;" class="imager-container" id="viewer1" name="files">
            @foreach (var item in Model.Images)
            {
                <label thumb-url='/uploads/homepagephotos/@item.FileName' image-id="@item.Id" @(item.IsMain == true ? "checked" : "")></label>
            }
        </div>
    </div>


    <div class="form-group">
        <input type="submit" value="Bazada Saxla" class="btn btn-success" />
    </div>

</form>
<a asp-controller="HomePageCRUD" asp-action="index" class="btn btn-primary">
    <spam>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-short" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z" />
        </svg>
    </spam>Geriyə

</a>

@section addcss{
    <script src="https://kit.fontawesome.com/1154e1d6ee.js" crossorigin="anonymous"></script>
    <link href="~/libs/multiple-imager-js/css/imager.css" rel="stylesheet" />
}


@section addjs{
    <script src="~/libs/jquery/jquery.min.js"></script>

    <script src="~/libs/multiple-imager-js/js/imager.js"></script>

    <script>
        $('#viewer1').imgadd({
            tnWidth: '120px',
            tnHeight: '120px',
            fontSize: '55px',
            plusInnerHtml: '',
            plusBtnClass: undefined
        });
    </script>
}

Krbprojects.WebUI/Areas/KrbAdmin/Views/HomePageCRUD/Index.cshtml
@model IEnumerable<HomePage>
<h1>Əsas səhifənin səkili</h1>
<a asp-controller="HomePageCRUD" asp-action="Create" class="btn btn-success">

    <span>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lightbulb" viewBox="0 0 16 16">
            <path d="M2 6a6 6 0 1 1 10.174 4.31c-.203.196-.359.4-.453.619l-.762 1.769A.5.5 0 0 1 10.5 13a.5.5 0 0 1 0 1 .5.5 0 0 1 0 1l-.224.447a1 1 0 0 1-.894.553H6.618a1 1 0 0 1-.894-.553L5.5 15a.5.5 0 0 1 0-1 .5.5 0 0 1 0-1 .5.5 0 0 1-.46-.302l-.761-1.77a1.964 1.964 0 0 0-.453-.618A5.984 5.984 0 0 1 2 6zm6-5a5 5 0 0 0-3.479 8.592c.263.254.514.564.676.941L5.83 12h4.342l.632-1.467c.162-.377.413-.687.676-.941A5 5 0 0 0 8 1z" />
        </svg>
    </span>Create
</a>
<table class="table">
    <thead>
        <tr>

            <th scope="col">Name</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in @Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>
                    @if (User.HasAccess("admin.HomePageCRUD.Edit"))
                    {
                        <a asp-controller="HomePageCRUD" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-secondary">

                            <span>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                    <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                                </svg>
                            </span>Edit
                        </a>

                    }
                    <br />
                    @if (User.HasAccess("admin.HomePageCRUD.Delete"))
                    {
                        <a asp-controller="HomePageCRUD" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">

                            <span>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                                </svg>
                            </span>Delete
                        </a>
                    }

                </td>
            </tr>


        }

    </tbody>
</table>