Krbprojects.WebUI/Areas/KrbAdmin/Controllers/ContactPagePhotoCRUDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Krbprojects.WebUI.Areas.KrbAdmin.Models.ViewModels;
using Krbprojects.WebUI.Models.DbContexts;
using Krbprojects.WebUI.Modules.ContactPagePhotoModel;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Krbprojects.WebUI.Areas.KrbAdmin.Controllers
{
    [Area("KrbAdmin")]
    public class ContactPagePhotoCRUDController : Controller
    {
        //teksekilli
        readonly KrbProjectsBaseDbContext db;
        readonly IMediator mediator;


        public ContactPagePhotoCRUDController(KrbProjectsBaseDbContext db, IMediator mediator)
        {
            this.db = db;
            this.mediator = mediator;
        }
        [Authorize(Policy = "admin.contactpagephotocrud.index")]
        public async Task<IActionResult> Index()
        {
            var photo = await db.ContactPagePhotos.ToListAsync();

            return View(photo);
        }
        [Authorize(Policy = "admin.contactpagephotocrud.delete")]

        public async Task<IActionResult> Delete(int id)
        {
            var photo = await db.ContactPagePhotos.FirstOrDefaultAsync(a => a.Id == id);
            return View(photo);
        }
        [Authorize(Policy = "admin.contactpagephotocrud.delete")]

        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var photo = await db.ContactPagePhotos.FirstOrDefaultAsync(a => a.Id == id);
            db.Remove(photo);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }





        [HttpGet]
        [Authorize(Policy = "admin.contactpagephotocrud.create")]

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Policy = "admin.contactpagephotocrud.create")]

        public async Task<IActionResult> Create(ContactPagePhotoCreateCommand info)
        {
            var response = await mediator.Send(info);
            return Redirect(nameof(Index));

        }

        [HttpGet]
        [Authorize(Policy = "admin.contactpagephotocrud.edit")]

        public async Task<IActionResult> Edit(int id)
        {
            var photo = await db.ContactPagePhotos.FirstOrDefaultAsync(a => a.Id == id);
            var model = new ContactPagePhotoViewModel();
            model.Id = photo.Id;
            model.Name = photo.Name;
            model.ImagePath = photo.ImagePath;
            return View(model);
        }

        [HttpPost]
        [Authorize(Policy = "admin.contactpagephotocrud.edit")]

        public async Task<IActionResult> Edit(ContactPagePhotoUpdateCommand information)
        {

            var response = await mediator.Send(information);

            return RedirectToAction(nameof(Index));
        }
    }
}

Krbprojects.WebUI/Areas/KrbAdmin/Views/ContactPagePhotoCRUD/Create.cshtml
@model ContactPagePhoto

<form asp-controller="ContactPagePhotoCRUD" asp-action="Create" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
   




    <div class="form-group ">
        <label class="control-label">
            Image
        </label>
        <label for="file" class="image-input">
            <input name="fileTemp" value="" type="hidden" />
            <span>x</span>
        </label>
        <input name="file" id="file" type="file" accept="image/x-png,image/gif,image/jpeg" />
    </div>


    <div class="form-group">
        <input type="submit" value="Bazada Saxla" class="btn btn-success" />
    </div>

</form>
<a asp-controller="ContactPagePhotoCRUD" asp-action="index" class="btn btn-primary">
    <spam>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-short" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z" />
        </svg>
    </spam>Geriyə

</a>

@section addcss{

    <link href="~/libs/jquery-image-input/image-input.css" rel="stylesheet" />
}

@section addjs{
    <script src="~/libs/ckeditor5/ckeditor.js"></script>
    <script src="~/libs/jquery-image-input/jquery.image-input.js"></script>
    <script>
        $(document).ready(function () {
            ClassicEditor
                .create(document.querySelector('#Content'))
                .catch(error => {
                    console.error(error);
                });
        })
    </script>
}

Krbprojects.WebUI/Areas/KrbAdmin/Views/ContactPagePhotoCRUD/Delete.cshtml
@model ContactPagePhoto
<h1>Silmək istədiyinizdən əminsinizsə davam edin</h1>

<form asp-controller="ContactPagePhotoCRUD" asp-action="Deleteconfirm" asp-route-id="@Model.Id">
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    
    <div class="form-group">
        <input type="submit" value="Davam et" class="btn btn-success" />
    </div>
</form>
<a asp-controller="ContactPagePhotoCRUD" asp-action="index" class="btn btn-primary">
    <spam>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-short" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z" />
        </svg>
    </spam>Geriyə

</a>

Krbprojects.WebUI/Areas/KrbAdmin/Views/ContactPagePhotoCRUD/Edit.cshtml
@model ContactPagePhotoViewModel
<form enctype="multipart/form-data" asp-controller="ContactPagePhotoCRUD" asp-action="Edit" asp-route-id="@Model.Id">
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group ">
        <label class="control-label">
            Image
        </label>
        <label for="file" class="image-input" data-imgurl="/uploads/images/@Model.ImagePath">
            <input name="fileTemp" value="@Model.ImagePath" type="hidden" />
            <span>x</span>
        </label>
        <input name="file" id="file" type="file" accept="image/x-png,image/gif,image/jpeg" />
    </div>


    <div class="form-group">
        <input type="submit" value="Yadda Saxla" class="btn btn-success" />
    </div>
</form>
<a asp-controller="ContactPagePhotoCRUD" asp-action="index" class="btn btn-primary">
    <spam>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-short" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z" />
        </svg>
    </spam>Geriyə

</a>
@section addcss{

    <link href="~/libs/jquery-image-input/image-input.css" rel="stylesheet" />
}


@section addjs{
    <script src="~/libs/ckeditor5/ckeditor.js"></script>
    <script src="~/libs/jquery-image-input/jquery.image-input.js"></script>
    <script>
        $(document).ready(function () {
            ClassicEditor
                .create(document.querySelector('#Content'))
                .catch(error => {
                    console.error(error);
                });
        })
    </script>
}

Krbprojects.WebUI/Areas/KrbAdmin/Views/ContactPagePhotoCRUD/Index.cshtml
@model IEnumerable<ContactPagePhoto>
<h1>Kontakt səhifəsnin şəkili</h1>
<a asp-controller="ContactPagePhotoCRUD" asp-action="Create" class="btn btn-success">

    <span>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lightbulb" viewBox="0 0 16 16">
            <path d="M2 6a6 6 0 1 1 10.174 4.31c-.203.196-.359.4-.453.619l-.762 1.769A.5.5 0 0 1 10.5 13a.5.5 0 0 1 0 1 .5.5 0 0 1 0 1l-.224.447a1 1 0 0 1-.894.553H6.618a1 1 0 0 1-.894-.553L5.5 15a.5.5 0 0 1 0-1 .5.5 0 0 1 0-1 .5.5 0 0 1-.46-.302l-.761-1.77a1.964 1.964 0 0 0-.453-.618A5.984 5.984 0 0 1 2 6zm6-5a5 5 0 0 0-3.479 8.592c.263.254.514.564.676.941L5.83 12h4.342l.632-1.467c.162-.377.413-.687.676-.941A5 5 0 0 0 8 1z" />
        </svg>
    </span>Create
</a>
<table class="table">
    <thead>
        <tr>

            <th scope="col">Name</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in @Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>
                    @if (User.HasAccess("admin.ContactPagePhotoCRUD.Edit"))
                    {
                        <a asp-controller="ContactPagePhotoCRUD" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-secondary">

                            <span>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                    <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                                </svg>
                            </span>Edit
                        </a>

                    }
                        <br />
                        @if (User.HasAccess("admin.ContactPagePhotoCRUD.Delete"))
                        {
                            <a asp-controller="ContactPagePhotoCRUD" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">

                                <span>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                                    </svg>
                                </span>Delete
                            </a>
                        }

                        </td>
            </tr>


        }

    </tbody>
</table>